# Generated by Django 3.2.9 on 2023-02-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(default=0)),
                ('running_status', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], default='stop', max_length=5)),
                ('operational', models.BooleanField(default=True)),
                ('door_status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', max_length=5)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.IntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.elevator')),
            ],
        ),
    ]
