# Generated by Django 3.2.9 on 2023-02-22 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='elevator',
            old_name='direction',
            new_name='initial_direction',
        ),
        migrations.AddField(
            model_name='elevator',
            name='lift_requested_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4),
        ),
        migrations.AddField(
            model_name='elevator',
            name='next_floor',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='requested_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default=None, max_length=4),
        ),
    ]
